import { useState } from 'react'
import { Link, useParams } from '@tanstack/react-router'
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Cable, CircleAlert, KeyRound, RefreshCw, Search, Settings2, Workflow } from 'lucide-react'
import { adaptersAPI } from '@/api'
import { adaptersQuery, qk, workflowsQuery } from '@/api/queries'
import { SchemaForm } from '@/components/schema-form'
import { PageHeading } from '@/components/page-heading'
import { StatusBadge } from '@/components/status-badge'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Confirm } from '@/components/ui/confirm'
import { EmptyState, ErrorState, LoadingState } from '@/components/query-state'
import { Input } from '@/components/ui/input'
import { useToast } from '@/components/ui/toast'
import { resourceLabel } from '@/lib/utils'
import { supportsCapability } from '@/lib/capabilities'
import type { Resource, ResourceRef } from '@/types/api'

type Tab = 'overview' | 'settings' | 'resources' | 'workflows'
export function AdapterDetailPage() {
  const { adapterId } = useParams({ from: '/adapters/$adapterId' }); const client = useQueryClient(); const { toast } = useToast()
  const [tab, setTab] = useState<Tab>('overview'); const [resource, setResource] = useState<ResourceRef>(); const [q, setQ] = useState(''); const [resourceType, setResourceType] = useState(''); const [searchTerm, setSearchTerm] = useState('')
  const adapter = useQuery({ queryKey: qk.adapter(adapterId), queryFn: () => adaptersAPI.get(adapterId) })
  const list = useQuery(adaptersQuery); const current = adapter.data ?? list.data?.find(item => item.status.id === adapterId); const descriptor = current?.descriptor
  const config = useQuery({ queryKey: qk.config(adapterId, resource), queryFn: () => adaptersAPI.config(adapterId, resource), enabled: Boolean(descriptor && tab === 'settings'), retry: false })
  const workflows = useQuery(workflowsQuery); const canBrowse = supportsCapability(current, 'resource_browse')
  const resources = useInfiniteQuery({ queryKey: qk.resources(adapterId, { q: searchTerm, resource, resourceType }), queryFn: ({ pageParam }) => adaptersAPI.resources(adapterId, { q: searchTerm || undefined, parent: resource, resource_type: resourceType || undefined, cursor: pageParam, limit: 20 }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor, enabled: Boolean(canBrowse && tab === 'resources' && descriptor), retry: false })
  const controls = useMutation({ mutationFn: (action: 'restart' | 'enable' | 'disable') => adaptersAPI.action(adapterId, action), onSuccess: result => { toast(`Adapter ${result.status.state}`); void client.invalidateQueries({ queryKey: qk.adapters }); void client.invalidateQueries({ queryKey: qk.adapter(adapterId) }) }, onError: error => toast('Adapter 작업 실패', String(error), 'error') })
  const save = useMutation({ mutationFn: (body: { values: Record<string, unknown>; secrets: Record<string, string>; clear_values: string[]; clear_secrets: string[] }) => adaptersAPI.saveConfig(adapterId, { ...body, resource }), onSuccess: () => { toast('설정을 저장했습니다.'); void client.invalidateQueries({ queryKey: qk.config(adapterId, resource) }) }, onError: error => toast('설정 저장 실패', String(error), 'error') })
  const allResourceTypes = descriptor?.resource_types ?? []
  const adapterWorkflows = workflows.data?.filter(item => item.adapter_id === adapterId) ?? []
  const resourceItems = resources.data?.pages.flatMap(page => page.items) ?? []
  if (adapter.isLoading) return <LoadingState />
  if (adapter.error || !current) return <ErrorState message={String(adapter.error ?? '어댑터를 찾을 수 없습니다.')} retry={() => void adapter.refetch()} />
  const tabs: { key: Tab; label: string; icon: typeof Cable; unavailable?: boolean }[] = [{ key: 'overview', label: '개요', icon: Cable }, { key: 'settings', label: '설정', icon: Settings2 }, { key: 'resources', label: '리소스', icon: Search, unavailable: !canBrowse }, { key: 'workflows', label: '워크플로', icon: Workflow }]
  return <div className="page-enter"><PageHeading eyebrow="ADAPTER DETAILS" title={descriptor?.name ?? current.status.name ?? adapterId} description={`${adapterId} · ${descriptor?.version ?? current.status.version ?? '버전 미보고'} · protocol ${descriptor?.protocol_version ?? current.status.protocol_version ?? '—'}`} actions={<>
    <Link to="/adapters"><Button variant="outline" size="sm"><ArrowLeft className="h-4 w-4" />목록</Button></Link>
    <Confirm trigger={<Button variant="outline" size="sm"><RefreshCw className="h-4 w-4" />Restart</Button>} title="Adapter process를 재시작할까요?" description="현재 adapter workflow는 종료될 수 있습니다. 이미 resolve된 recording은 계속 acquisition합니다." confirmLabel="재시작" onConfirm={() => controls.mutate('restart')} disabled={controls.isPending} />
    {current.status.state === 'disabled' ? <Confirm trigger={<Button size="sm">Enable</Button>} title="Adapter를 활성화할까요?" description="활성화 이후 adapter를 새 recording resolution에 사용할 수 있습니다." confirmLabel="활성화" onConfirm={() => controls.mutate('enable')} disabled={controls.isPending} /> : <Confirm trigger={<Button variant="destructive" size="sm">Disable</Button>} title="Adapter를 비활성화할까요?" description="새 recording resolution이 차단됩니다. 이미 resolve된 recording은 영향을 받지 않습니다." confirmLabel="비활성화" destructive onConfirm={() => controls.mutate('disable')} disabled={controls.isPending} />}
  </>} />
    <div className="mb-4 flex gap-1 overflow-x-auto border-b border-border">{tabs.filter(item => !item.unavailable).map(item => <button key={item.key} role="tab" aria-selected={tab === item.key} onClick={() => setTab(item.key)} className={`focus-ring inline-flex min-w-max items-center gap-2 border-b-2 px-3 py-2.5 text-sm ${tab === item.key ? 'border-primary font-semibold text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}><item.icon className="h-4 w-4" />{item.label}</button>)}</div>
    {tab === 'overview' && <div className="grid gap-4 xl:grid-cols-[1fr_.75fr]"><Card><CardHeader><CardTitle>Descriptor</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2">{[['ID', descriptor?.id ?? current.status.id], ['Name', descriptor?.name ?? current.status.name ?? '—'], ['Version', descriptor?.version ?? current.status.version ?? '—'], ['Protocol', `v${descriptor?.protocol_version ?? current.status.protocol_version ?? '—'}`], ['Generation', current.status.generation ?? '—'], ['Restart attempts', current.status.restart_attempts ?? 0]].map(([label, value]) => <Info key={String(label)} label={String(label)} value={String(value)} />)}</div><div className="mt-5 border-t border-border pt-4"><p className="text-xs font-semibold">Capabilities</p><div className="mt-2 flex flex-wrap gap-1.5">{descriptor?.capabilities?.map(cap => <Badge key={cap} tone="blue">{cap}</Badge>) ?? <span className="text-xs text-muted-foreground">미보고</span>}</div></div><div className="mt-4"><p className="text-xs font-semibold">Media types</p><div className="mt-2 flex flex-wrap gap-1.5">{descriptor?.media_types.map(type => <Badge key={type}>{type}</Badge>)}</div></div></CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle>Runtime 상태</CardTitle></CardHeader><CardContent><StatusBadge state={current.status.state} />{current.status.error && <p className="mt-3 flex items-start gap-2 rounded-md bg-amber-500/10 p-3 text-xs leading-5 text-amber-800 dark:text-amber-200"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />{current.status.error}</p>}<p className="mt-3 text-xs text-muted-foreground">Adapter process는 Core와 같은 OS user 권한으로 실행됩니다.</p></CardContent></Card><Card><CardHeader><CardTitle>Resource type declarations</CardTitle></CardHeader><CardContent>{allResourceTypes.length ? <div className="space-y-3">{allResourceTypes.map(item => <div key={item.type} className="rounded-md border border-border p-3"><p className="font-mono text-sm">{item.type}</p><p className="mt-1 text-xs text-muted-foreground">허용 parent: {item.parent_types?.join(', ') || 'root'}</p></div>)}</div> : <p className="text-sm text-muted-foreground">Resource type을 선언하지 않았습니다.</p>}</CardContent></Card></div></div>}
    {tab === 'settings' && <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><Card><CardHeader><CardTitle>Adapter-defined settings</CardTitle><p className="text-sm text-muted-foreground">입력 종류와 제약 조건은 adapter schema가 선언합니다. 비밀 값은 되돌려 표시하지 않습니다.</p></CardHeader><CardContent>{config.isLoading ? <LoadingState /> : config.error || !config.data ? <ErrorState message={String(config.error ?? '설정을 불러올 수 없습니다.')} retry={() => void config.refetch()} /> : config.data.schema.fields.length ? <SchemaForm schema={config.data.schema} initialValues={config.data.effective.values} storedValues={config.data.stored.values} initialSecrets={config.data.effective.secrets} valueSources={config.data.value_sources} secretSources={config.data.secret_sources} mode="config" submitLabel="설정 저장" onSubmit={result => save.mutate({ values: result.values, secrets: result.secrets, clear_values: result.clearValues, clear_secrets: result.clearSecrets })} busy={save.isPending} /> : <EmptyState title="설정 가능한 항목이 없습니다." />}</CardContent></Card><div className="space-y-4"><ConfigScopeSelector adapterId={adapterId} resource={resource} onSelect={setResource} canBrowse={canBrowse} /></div></div>}
    {tab === 'resources' && canBrowse && <Card><CardHeader><CardTitle>Opaque resource browser</CardTitle><p className="text-sm text-muted-foreground">Core는 resource type과 ID의 의미를 해석하지 않습니다.</p></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-[1fr_190px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={q} onChange={event => setQ(event.target.value)} onKeyDown={event => event.key === 'Enter' && setSearchTerm(q)} placeholder="Resource 이름 검색" /></div><Input value={resourceType} onChange={event => setResourceType(event.target.value)} placeholder="Resource type" /><Button onClick={() => setSearchTerm(q)}><Search className="h-4 w-4" />검색</Button></div>{resource && <p className="mt-3 text-xs text-muted-foreground">Parent scope: {resourceLabel(resource)}</p>}{resources.isLoading ? <LoadingState /> : resources.error ? <ErrorState message={String(resources.error)} retry={() => void resources.refetch()} /> : resourceItems.length ? <div className="mt-4 divide-y divide-border">{resourceItems.map((item, index) => <div key={`${item.resource_type}-${item.resource_id}-${index}`} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.display_name ?? item.resource_id}</p><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{item.resource_type} / {item.resource_id}</p>{item.parent && <p className="mt-1 truncate text-[10px] text-muted-foreground">parent: {resourceLabel(item.parent)}</p>}</div><Button variant="outline" size="sm" onClick={() => setResource({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent })}>하위 resource 탐색</Button><Button size="sm" onClick={() => { setResource({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent }); setTab('settings') }}>이 scope 설정</Button></div>)}</div> : <EmptyState title="표시할 resource가 없습니다." description="Adapter가 반환한 결과가 없거나 검색 결과가 없습니다." />}{resources.hasNextPage && <Button variant="outline" size="sm" className="mt-3" onClick={() => void resources.fetchNextPage()} disabled={resources.isFetchingNextPage}>{resources.isFetchingNextPage ? '불러오는 중…' : '더 보기'}</Button>}</CardContent></Card>}
    {tab === 'workflows' && <Card><CardHeader><CardTitle>Adapter workflows</CardTitle><p className="text-sm text-muted-foreground">활성 workflow는 adapter process generation에 연결됩니다.</p></CardHeader><CardContent>{adapterWorkflows.length ? <div className="divide-y divide-border">{adapterWorkflows.map(workflow => <Link key={workflow.workflow_id} to="/workflows/$workflowId" params={{ workflowId: workflow.workflow_id }} className="flex items-center justify-between gap-3 py-3"><span><span className="block text-sm font-medium">{workflow.workflow_id}</span><span className="mt-1 block text-xs text-muted-foreground">{workflow.state} · expires {new Date(workflow.expires_at).toLocaleString()}</span></span><StatusBadge state={workflow.state} /></Link>)}</div> : <EmptyState title="활성 workflow가 없습니다." />}</CardContent></Card>}
  </div>
}
function Info({ label, value }: { label: string; value: string | number }) { return <div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm font-medium">{value}</p></div> }
function ConfigScopeSelector({ adapterId, resource, onSelect, canBrowse }: { adapterId: string; resource?: ResourceRef; onSelect: (resource?: ResourceRef) => void; canBrowse: boolean }) {
  const [q, setQ] = useState(''); const [search, setSearch] = useState(''); const [resourceType, setResourceType] = useState('')
  const query = useQuery({ queryKey: qk.resources(adapterId, { search, resourceType }), queryFn: () => adaptersAPI.resources(adapterId, { q: search || undefined, resource_type: resourceType || undefined, limit: 20 }), enabled: Boolean(canBrowse && search.length >= 2), retry: false })
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-4 w-4" />설정 범위</CardTitle><p className="text-xs text-muted-foreground">현재 편집 범위: {resource ? resourceLabel(resource) : 'Adapter 공통'}</p></CardHeader><CardContent><Button variant={!resource ? 'secondary' : 'outline'} size="sm" onClick={() => onSelect(undefined)}>Adapter 공통 범위</Button>{canBrowse && <><div className="mt-3 flex gap-2"><Input value={q} onChange={event => setQ(event.target.value)} placeholder="Resource 검색" aria-label="설정 scope 검색" /><Button variant="outline" size="sm" onClick={() => setSearch(q)}>검색</Button></div><Input className="mt-2" value={resourceType} onChange={event => setResourceType(event.target.value)} placeholder="Resource type (optional)" aria-label="Resource type" />{query.data?.items.map((item: Resource, index: number) => <button key={`${item.resource_type}-${item.resource_id}-${index}`} className="mt-2 block w-full rounded-md border border-border p-2 text-left hover:bg-muted" onClick={() => onSelect({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent })}><span className="block truncate text-xs font-medium">{item.display_name ?? item.resource_id}</span><span className="block truncate text-[10px] text-muted-foreground">{item.resource_type}</span></button>)}</>}<p className="mt-3 text-[11px] leading-5 text-muted-foreground">다른 scope에서 상속된 값은 표시되며, 변경하면 이 범위에 override가 저장됩니다.</p></CardContent></Card>
}
